### ISSUE TITLE
fix: `grafana/wait-for-github` status checks stay `pending`

### ISSUE THREAD

**Issue by ricky-undeadcoders** [grafana/wait-for-github#153]
There is an issue with how we perform status checks in `grafana/wait-for-github` in Argo Workflows. For CD jobs such as [this one](https://argo-workflows.grafana.net/workflows/phlare-cd/phlare-cd-phlare-create-deployment-monday-ops-1721008800) for Pyroscope we perform a [status check](https://api.github.com/repos/grafana/pyroscope/commits/feefa815b3f141878abf5f1bf79f470ad4031f08/status) against the GitHub API for the branch that triggered the build, which stays in a pending state, regardless of any actions that might be running for that branch.

In the case of the Pyroscope job listed above we should have found [this Action](https://github.com/grafana/pyroscope/actions/runs/10045973585/job/27764431875), and waited for it to complete before moving on.

The fix for this is to add an extra step somewhere in the the [GetCIStatus](https://github.com/grafana/wait-for-github/blob/main/internal/github/github.go#L185) check that will look at GitHub actions that are running for the branch and determine a status based off of the state of those workflows.

See this discussion for more insight into the issue: https://github.com/orgs/community/discussions/58407

**Comment by guicaulada** [comment]
Testing with `gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/grafana/deployment_tools/commits/045b18a023af83f5689492494432004c770285fc/status` it seems the API always returns `"statuses": []` and `"status": "pending"`, even though all workflows finished running.

**Comment by iainlane** [comment]
I accidentally worked on this before noticing Gui had claimed it, so stealing the assignment (after chatting in private). Soz!
